### ISSUE TITLE
Don't need export

### ISSUE THREAD

**Issue by joshteng** [rygo2765/luno-premium-sol#1]
https://github.com/rygo2765/luno-premium-sol/blob/df3c73a8171cf513bce0e74c3c1383042226a35d/index.js#L7

Just a quick glance, don't see this function being used anywhere else. Can avoid `export`.

If there is a need to export, we generally put them into its own `module` / `file`

**Comment by rygo2765** [comment]
im using the export for integration test (index.test.js)
