### ISSUE TITLE
Create new Error

### ISSUE THREAD

**Issue by joshteng** [rygo2765/luno-premium-sol#6]
https://github.com/rygo2765/luno-premium-sol/blob/df3c73a8171cf513bce0e74c3c1383042226a35d/lib/binance.js#L15

I think I used to use this a lot in class. A better approach is

```js
throw new Error(`Fetch failed`)
```

An even better approach is something like this:

```js
class ValidationError extends Error {
  constructor(message) {
    super(message); // (1)
    this.name = "ValidationError"; // (2)
  }
}

function test() {
  throw new ValidationError("Whoops!");
}

try {
  test();
} catch(err) {
  alert(err.message); // Whoops!
  alert(err.name); // ValidationError
  alert(err.stack); // a list of nested calls with line numbers for each
}
```
stole this code from https://javascript.info/custom-errors

**Comment by rygo2765** [comment]
`throw new Error(`Fetch failed`)
`
why is this better?
